import { ThemeContextProvider } from "@/context/themeContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <ThemeContextProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    {children}{" "}
                </ThemeContextProvider>
            </body>
        </html>
    );
}
